[build]
  command = "npx prisma generate && npx prisma db push --skip-generate && npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/.prisma/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[images]
  remote_images = []
